handle unset webhook url

diff --git a/done b/done
--- a/done
+++ b/done
@@ -7,6 +7,10 @@ exit_code=$4
 command=$SLURM_EXEC_COMMAND
 
 url=$TEAMS_SLURM_WEBHOOK
+if [ -z "$url" ]; then
+    echo "Error: TEAMS_SLURM_WEBHOOK is not set"
+    exit 1
+fi
 
 if [ "$exit_code" -eq 0 ]; then
     theme_color="0072C6" # blue
diff --git a/start b/start
--- a/start
+++ b/start
@@ -6,6 +6,10 @@ partition=$3
 command=$SLURM_EXEC_COMMAND
 
 url=$TEAMS_SLURM_WEBHOOK
+if [ -z "$url" ]; then
+    echo "Error: TEAMS_SLURM_WEBHOOK is not set"
+    exit 1
+fi
 
 theme_color="C274E3"
 title="🚀 Job ($job_id: $job_name) is started ($partition)"
